<?php

/**
 * ============================================================================
 *  Zeportic — Zammad Reporting Tool — Config loader & setup state
 * ============================================================================
 *
 *  Configuration model
 *  -------------------
 *  1. config.php        — the shipped, versioned base config (safe defaults).
 *  2. config.local.php  — OPTIONAL override written by the graphical setup
 *                         wizard (setup.php). Never committed to git; delete
 *                         it to re-run the wizard.
 *
 *  Config::load() deep-merges (2) over (1), so both the wizard output and a
 *  hand-edited config.php work side by side.
 *
 *  "Configured" state
 *  ------------------
 *  isConfigured() returns true when EITHER:
 *    - config.local.php exists (the wizard finished at least once), OR
 *    - config.php no longer contains the shipped placeholder values
 *      (i.e. the user configured everything manually).
 *  While not configured, index.php redirects to setup.php — the graphical
 *  first-run wizard.
 * ----------------------------------------------------------------------------
 */

declare(strict_types=1);

final class Config
{
    /** All shipped UI language codes — keep in sync with assets/lang/meta.js. */
    public const LANGS = [
        'en', 'fa', 'ar', 'he', 'ur', 'de', 'fr', 'es', 'pt', 'it', 'nl',
        'pl', 'cs', 'el', 'ru', 'uk', 'tr', 'sv', 'id', 'vi', 'hi', 'th',
        'ja', 'ko', 'zh-cn', 'zh-tw',
    ];

    /** Right-to-left languages (flip the whole layout). */
    public const RTL = ['fa', 'ar', 'he', 'ur'];

    /** The ES password placeholder shipped in config.php. */
    public const PLACEHOLDER_ES_PASSWORD = 'CHANGE_ME_ELASTIC_PASSWORD';

    public static function basePath(): string
    {
        return BASE_DIR . '/config.php';
    }

    public static function localPath(): string
    {
        return BASE_DIR . '/config.local.php';
    }

    /**
     * Full effective configuration: config.php deep-merged with
     * config.local.php (when present).
     */
    public static function load(): array
    {
        $config = require self::basePath();
        if (!is_array($config)) {
            return [];
        }
        $local = self::local();
        return $local !== null ? self::merge($config, $local) : $config;
    }

    /** The wizard-written override file, or null when it does not exist. */
    public static function local(): ?array
    {
        $path = self::localPath();
        if (!is_file($path)) {
            return null;
        }
        $local = require $path;
        return is_array($local) ? $local : null;
    }

    /**
     * True when the app has usable Elasticsearch credentials — either the
     * setup wizard has run (config.local.php exists) or the user replaced
     * the shipped placeholders manually in config.php.
     */
    public static function isConfigured(): bool
    {
        if (is_file(self::localPath())) {
            return true;
        }
        if (!is_file(self::basePath())) {
            return false;
        }
        $base = require self::basePath();
        if (!is_array($base)) {
            return false;
        }
        $esPass = (string)($base['elasticsearch']['password'] ?? '');
        return $esPass !== '' && $esPass !== self::PLACEHOLDER_ES_PASSWORD;
    }

    /**
     * Persist the wizard output as config.local.php.
     * The file is written atomically (tmp + rename) and carries the usual
     * APP_RUNNING guard so it can never be served over HTTP.
     */
    public static function saveLocal(array $local): void
    {
        $code = "<?php\n"
            . "/*\n * Generated by the Zeportic setup wizard on " . date('Y-m-d H:i') . ".\n"
            . " * Edit the values below — or delete this file — to re-run setup (setup.php).\n"
            . " * This file is git-ignored and must never be committed.\n */\n"
            . "defined('APP_RUNNING') or die('No direct access');\n\nreturn ";

        $code .= var_export($local, true) . ";\n";

        $tmp = self::localPath() . '.' . getmypid() . '.tmp';
        if (@file_put_contents($tmp, $code, LOCK_EX) === false) {
            throw new RuntimeException(
                'Cannot write the configuration file. Make the Zeportic folder writable for the web server user (e.g. chown -R www-data:www-data /opt/zeportic).'
            );
        }
        if (!@rename($tmp, self::localPath())) {
            @unlink($tmp);
            throw new RuntimeException('Could not finalize the configuration file (rename failed). Check folder permissions.');
        }
        @chmod(self::localPath(), 0640);
    }

    /** Recursive array merge — override values win, keys keep base order. */
    private static function merge(array $base, array $override): array
    {
        foreach ($override as $key => $value) {
            if (is_array($value) && isset($base[$key]) && is_array($base[$key])) {
                $base[$key] = self::merge($base[$key], $value);
            } else {
                $base[$key] = $value;
            }
        }
        return $base;
    }
}
